spring:
  profiles:
    active: local

server:
  port: 9091
  api:
    listen:
      host: 0.0.0.0
      port: 3003
camel:
  component: jetty
  springboot:
    main-run-controller: true
    name: mojaloop-finflux-core-connector
    stream-caching-enabled: true

# the below properties are here for development reference purpose
# for the cluster usage it are being set through system variable (java -Dcbs.host=... -Dcbs.username=... -jar core-connector.jar) into Dockerfile
#cbs:
#  host: https://localhost/api
#  username: user
#  password: pass
#  clientId: id
#  clientSecret: secret
#  grantType: type
#  scope: scope
#  isPasswordEncrypted: false
#  tenantId: id

#mlConnector:
#  outbound:
#    host:  http://localhost:3004